TritonExpress01/TritonMVC/Models/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TritonMVC.Models
{
    public class VehicleViewModel
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Branch")]
        public string branch { get; set; }
        [Display(Name = "Vehicle Year")]
        public Nullable<int> vehicleyear { get; set; }
        [Display(Name = "Vehicle Make")]
        public string vehiclemake { get; set; }
        [Display(Name = "Vehicle Model")]
        public string vehiclemodel { get; set; }
        [Required]
        [Display(Name = "Vehicle Registration")]
        public string vehiclereg { get; set; }
        [Display(Name = "WayBill")]
        public Nullable<int> wayBillID { get; set; }

        [NotMapped]
        public List<SelectListItem> branches = new List<SelectListItem>
        {
        new SelectListItem { Value = "Durban", Text = "Durban" },
        new SelectListItem { Value = "Johannesburg", Text = "Johannesburg" },
        };
    }
}

TritonExpress01/TritonMVC/Models/WaybillViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TritonMVC.Models
{
    public class WaybillViewModel
    {
        public int wayBillID { get; set; }
        [Display(Name = "Recipient Name")]
        public string RecipientName { get; set; }
        [Display(Name = "Address")]
        public string Address { get; set; }
        public string Cell { get; set; }
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
        [Required]
        [Display(Name = "WayBill Information")]
        public string WayBillInfo { get; set; }
        [Display(Name = "WayBill Weight")]
        public string WayBillweight { get; set; }
        [Display(Name = "Total Items")]
        public string NumberOfParcels { get; set; }
    }
}

TritonExpress01/TritonMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TritonMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TritonExpress01/TritonMVC/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TritonMVC.Models;

namespace TritonMVC.Controllers
{
    public class VehicleController : Controller
    {
        // GET: Vehicle
        public ActionResult Index(string searchString)
        {
            
            ViewData["CurrentFilter"] = searchString;
            IEnumerable<VehicleViewModel> vehicleList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TritonExpressVehicles").Result;
            vehicleList = response.Content.ReadAsAsync<IEnumerable<VehicleViewModel>>().Result;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                vehicleList = vehicleList.Where(s => s.vehiclemake.ToLower().Contains(searchString)
                                       || s.vehiclemodel.ToLower().Contains(searchString)
                                       || s.vehiclereg.ToLower().Contains(searchString)
                                       || Convert.ToString(s.vehicleyear).Contains(searchString)
                                       || Convert.ToString(s.wayBillID).Contains(searchString)
                                       || s.branch.ToLower().Contains(searchString));
            }

            return View(vehicleList);
        }

        public ActionResult AddorEdit(int id = 0)
        {
            List<WaybillViewModel> tritonwaybillList = new List<WaybillViewModel>();
            HttpResponseMessage waybillresponse = GlobalVariables.WebApiClient.GetAsync("TritonExpressWaybills").Result;
            tritonwaybillList = waybillresponse.Content.ReadAsAsync<List<WaybillViewModel>>().Result;
            ViewBag.ListOfWaybill = tritonwaybillList;

            if (id == 0)
            {
                return View(new VehicleViewModel());
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TritonExpressVehicles/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<VehicleViewModel>().Result);
            }
        }
        [HttpPost]
        public ActionResult AddorEdit(VehicleViewModel veh)
        {
            if (veh.ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("TritonExpressVehicles", veh).Result;
                TempData["SuccessV"] = "Save Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("TritonExpressVehicles/" + veh.ID, veh).Result;
                TempData["SuccessV"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("TritonExpressVehicles/" + id.ToString()).Result;
            TempData["SuccessV"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

TritonExpress01/TritonMVC/Controllers/WaybillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TritonMVC.Models;

namespace TritonMVC.Controllers
{
    public class WaybillController : Controller
    {
        // GET: Waybill
        public ActionResult Index(string searchString)
        {
            
            ViewData["CurrentFilter"] = searchString;
            IEnumerable<WaybillViewModel> waybillList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TritonExpressWaybills").Result;
            waybillList = response.Content.ReadAsAsync<IEnumerable<WaybillViewModel>>().Result;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                waybillList = waybillList.Where(s => s.RecipientName.ToLower().Contains(searchString)
                                       || s.Address.ToLower().Contains(searchString)
                                       || s.Cell.ToLower().Contains(searchString)
                                       || s.WayBillInfo.ToLower().Contains(searchString)
                                       || s.WayBillweight.ToLower().Contains(searchString)
                                       || s.NumberOfParcels.ToLower().Contains(searchString));
            }

            return View(waybillList);
        }

        public ActionResult AddorEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new WaybillViewModel());
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TritonExpressWaybills/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<WaybillViewModel>().Result);
            }
        }
        [HttpPost]
        public ActionResult AddorEdit(WaybillViewModel way)
        {
            if (way.wayBillID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("TritonExpressWaybills", way).Result;
                TempData["SuccessW"] = "Save Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("TritonExpressWaybills/" + way.wayBillID, way).Result;
                TempData["SuccessW"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("TritonExpressWaybills/" + id.ToString()).Result;
            TempData["SuccessW"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

TritonExpress01/TritonMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TritonExpress01/TritonMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TritonExpress01/TritonMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TritonExpress01/TritonMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Triton Express", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Ashley Naidu - Triton Express Test Assessment</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TritonExpress01/TritonMVC/Views/Vehicle/AddorEdit.cshtml
@model TritonMVC.Models.VehicleViewModel

@{
    ViewBag.Title = "AddorEdit";
}

<h2>New/Update Vehicle</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <div class="form-group">
        @Html.LabelFor(model => model.branch, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.branch, new SelectList(Model.branches, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.branch, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.vehicleyear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.vehicleyear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.vehicleyear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.vehiclemake, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.vehiclemake, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.vehiclemake, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.vehiclemodel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.vehiclemodel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.vehiclemodel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.vehiclereg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.vehiclereg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.vehiclereg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.wayBillID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.wayBillID, new SelectList(ViewBag.ListOfWaybill, "wayBillID", "wayBillID"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.wayBillID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add/Update" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TritonExpress01/TritonMVC/Views/Vehicle/Index.cshtml
@model IEnumerable<TritonMVC.Models.VehicleViewModel>

@{
    ViewBag.Title = "Index";
}

<br />

<p>
    <a href="@Url.Action("AddOrEdit","Vehicle")" class="btn btn-primary"><i class="fa fa-plus"></i>Add New Vehicle</a>@*@Html.ActionLink("Create New", "Create")*@
</p>
<p>
    <a href="@Url.Action("Index","Waybill")" class="btn btn-light">Go To Waybills</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color" style="float:right">
        <p>
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-secondary" />
        </p>
    </div>
</form>

<table class="table table-striped">
    <thead class="table-heading">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.branch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicleyear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehiclemake)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehiclemodel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehiclereg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wayBillID)
            </th>
            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.branch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vehicleyear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vehiclemake)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vehiclemodel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vehiclereg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.wayBillID)
            </td>
            <td>
                <a href="@Url.Action("AddOrEdit","Vehicle",new {id = item.ID })" class="btn btn-default"><i class="fa fa-pencil"></i>Edit</a>
                @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                <a onclick="Delete(@item.ID)" class="btn btn-default"><i class="fa fa-trash"></i>Delete</a>
            </td>
        </tr>
    }

</table>


@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessV"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        function Delete(id) {
            alertify.confirm('Delete!', 'Are you sure?', function () {
                window.location.href = '@Url.Action("Delete","Vehicle")/' + id;
            }, null);
        }
    </script>
}