TritonExpress/Models/TritonExpressWaybill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TritonExpress.Models
{
    public class TritonExpressWaybill
    {
        [Key]
        public int wayBillID { get; set; }
        [Display(Name = "Recipient Name")]
        public string RecipientName { get; set; }
        [Display(Name = "Address")]
        public string Address { get; set; }
        [Display(Name = "Contact Number")]
        public string Cell { get; set; }
        [Display(Name = "Date")]
        public DateTime Date { get; set; }
        [Required]
        [Display(Name = "WayBill Information")]
        public string WayBillInfo { get; set; }
        [Display(Name = "WayBill Weight")]
        public string WayBillweight { get; set; }
        [Display(Name = "Total Items")]
        public string NumberOfParcels { get; set; }
    }
}

TritonExpress/Controllers/TritonExpressVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TritonExpress.Models;

namespace TritonExpress.Controllers
{
    public class TritonExpressVehiclesController : Controller
    {
        private readonly TritonExpressContext _context;

        public TritonExpressVehiclesController(TritonExpressContext context)
        {
            _context = context;
        }

        // GET: TritonExpressVehicles
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var vehicle = from s in _context.TritonExpressVehicle
                          select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                vehicle = vehicle.Where(s => s.vehiclemake.Contains(searchString)
                                       || s.vehiclemodel.Contains(searchString)
                                       || s.vehiclereg.Contains(searchString)
                                       || Convert.ToString(s.vehicleyear).Contains(searchString)
                                       || Convert.ToString(s.wayBillID).Contains(searchString)
                                       || s.branch.Contains(searchString));
            }
            return View(await vehicle.AsNoTracking().ToListAsync());
        }

        // GET: TritonExpressVehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressVehicle = await _context.TritonExpressVehicle
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tritonExpressVehicle == null)
            {
                return NotFound();
            }

            return View(tritonExpressVehicle);
        }

        // GET: TritonExpressVehicles/Create
        public IActionResult Create()
        {
            TritonExpressVehicle model = new TritonExpressVehicle();
            model.branch = "Select";

            List<TritonExpressWaybill> tritonwaybillList = new List<TritonExpressWaybill>();

            tritonwaybillList = (from waybill in _context.TritonExpressWaybill
                             select waybill).ToList();
            tritonwaybillList.Insert(0, new TritonExpressWaybill { wayBillID = 0, RecipientName = "Select" });
            ViewBag.ListOfWaybill = tritonwaybillList;

            return View(model);
        }

        // POST: TritonExpressVehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,branch,vehicleyear,vehiclemake,vehiclemodel,vehiclereg,wayBillID")] TritonExpressVehicle tritonExpressVehicle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tritonExpressVehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tritonExpressVehicle);
        }

        // GET: TritonExpressVehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressVehicle = await _context.TritonExpressVehicle.FindAsync(id);
            if (tritonExpressVehicle == null)
            {
                return NotFound();
            }
            tritonExpressVehicle.branch = "Select";
            List<TritonExpressWaybill> tritonwaybillList = new List<TritonExpressWaybill>();

            tritonwaybillList = (from waybill in _context.TritonExpressWaybill
                                 select waybill).ToList();
            tritonwaybillList.Insert(0, new TritonExpressWaybill { wayBillID = 0, RecipientName = "Select" });
            ViewBag.ListOfWaybillEdit = tritonwaybillList;
            return View(tritonExpressVehicle);
        }

        // POST: TritonExpressVehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,branch,vehicleyear,vehiclemake,vehiclemodel,vehiclereg,wayBillID")] TritonExpressVehicle tritonExpressVehicle)
        {
            if (id != tritonExpressVehicle.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tritonExpressVehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TritonExpressVehicleExists(tritonExpressVehicle.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tritonExpressVehicle);
        }

        // GET: TritonExpressVehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressVehicle = await _context.TritonExpressVehicle
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tritonExpressVehicle == null)
            {
                return NotFound();
            }

            return View(tritonExpressVehicle);
        }

        // POST: TritonExpressVehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tritonExpressVehicle = await _context.TritonExpressVehicle.FindAsync(id);
            _context.TritonExpressVehicle.Remove(tritonExpressVehicle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TritonExpressVehicleExists(int id)
        {
            return _context.TritonExpressVehicle.Any(e => e.ID == id);
        }

        public ActionResult Changes()
        {
            return RedirectToAction("Index", "TritonExpressWaybills");
        }
    }
}

TritonExpress/Controllers/TritonExpressWaybillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TritonExpress.Models;

namespace TritonExpress.Controllers
{
    public class TritonExpressWaybillsController : Controller
    {
        private readonly TritonExpressContext _context;

        public TritonExpressWaybillsController(TritonExpressContext context)
        {
            _context = context;
        }

        // GET: TritonExpressWaybills
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;
            var waybill = from s in _context.TritonExpressWaybill
                          select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                waybill = waybill.Where(s => s.RecipientName.Contains(searchString)
                                       || s.Address.Contains(searchString)
                                       || s.Cell.Contains(searchString)
                                       || s.WayBillInfo.Contains(searchString)
                                       || s.WayBillweight.Contains(searchString)
                                       || s.NumberOfParcels.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    waybill = waybill.OrderByDescending(s => s.RecipientName);
                    break;
                case "Date":
                    waybill = waybill.OrderBy(s => s.Date);
                    break;
                case "date_desc":
                    waybill = waybill.OrderByDescending(s => s.Date);
                    break;
                default:
                    waybill = waybill.OrderBy(s => s.RecipientName);
                    break;
            }
            return View(await waybill.AsNoTracking().ToListAsync());
        }

        // GET: TritonExpressWaybills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressWaybill = await _context.TritonExpressWaybill
                .FirstOrDefaultAsync(m => m.wayBillID == id);
            if (tritonExpressWaybill == null)
            {
                return NotFound();
            }

            return View(tritonExpressWaybill);
        }

        // GET: TritonExpressWaybills/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TritonExpressWaybills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("wayBillID,RecipientName,Address,Cell,Date,WayBillInfo,WayBillweight,NumberOfParcels")] TritonExpressWaybill tritonExpressWaybill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tritonExpressWaybill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tritonExpressWaybill);
        }

        // GET: TritonExpressWaybills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressWaybill = await _context.TritonExpressWaybill.FindAsync(id);
            if (tritonExpressWaybill == null)
            {
                return NotFound();
            }
            return View(tritonExpressWaybill);
        }

        // POST: TritonExpressWaybills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("wayBillID,RecipientName,Address,Cell,Date,WayBillInfo,WayBillweight,NumberOfParcels")] TritonExpressWaybill tritonExpressWaybill)
        {
            if (id != tritonExpressWaybill.wayBillID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tritonExpressWaybill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TritonExpressWaybillExists(tritonExpressWaybill.wayBillID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tritonExpressWaybill);
        }

        // GET: TritonExpressWaybills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tritonExpressWaybill = await _context.TritonExpressWaybill
                .FirstOrDefaultAsync(m => m.wayBillID == id);
            if (tritonExpressWaybill == null)
            {
                return NotFound();
            }

            return View(tritonExpressWaybill);
        }

        // POST: TritonExpressWaybills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tritonExpressWaybill = await _context.TritonExpressWaybill.FindAsync(id);
            _context.TritonExpressWaybill.Remove(tritonExpressWaybill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TritonExpressWaybillExists(int id)
        {
            return _context.TritonExpressWaybill.Any(e => e.wayBillID == id);
        }
    }
}

TritonExpress/Views/TritonExpressWaybills/Create.cshtml
@model TritonExpress.Models.TritonExpressWaybill

@{
    ViewData["Title"] = "Create";
}

<h2>New WayBill</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecipientName" class="control-label"></label>
                <input asp-for="RecipientName" class="form-control" />
                <span asp-validation-for="RecipientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cell" class="control-label"></label>
                <input asp-for="Cell" class="form-control" />
                <span asp-validation-for="Cell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WayBillInfo" class="control-label"></label>
                <input asp-for="WayBillInfo" class="form-control" />
                <span asp-validation-for="WayBillInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WayBillweight" class="control-label"></label>
                <input asp-for="WayBillweight" class="form-control" />
                <span asp-validation-for="WayBillweight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfParcels" class="control-label"></label>
                <input asp-for="NumberOfParcels" class="form-control" />
                <span asp-validation-for="NumberOfParcels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TritonExpress/Views/TritonExpressWaybills/Delete.cshtml
@model TritonExpress.Models.TritonExpressWaybill

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WayBillInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WayBillInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WayBillweight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WayBillweight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfParcels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfParcels)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="wayBillID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TritonExpress/Views/TritonExpressWaybills/Details.cshtml
@model TritonExpress.Models.TritonExpressWaybill

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WayBillInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WayBillInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WayBillweight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WayBillweight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfParcels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfParcels)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.wayBillID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TritonExpress/Views/TritonExpressWaybills/Edit.cshtml
@model TritonExpress.Models.TritonExpressWaybill

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="wayBillID" />
            <div class="form-group">
                <label asp-for="RecipientName" class="control-label"></label>
                <input asp-for="RecipientName" class="form-control" />
                <span asp-validation-for="RecipientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cell" class="control-label"></label>
                <input asp-for="Cell" class="form-control" />
                <span asp-validation-for="Cell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WayBillInfo" class="control-label"></label>
                <input asp-for="WayBillInfo" class="form-control" />
                <span asp-validation-for="WayBillInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WayBillweight" class="control-label"></label>
                <input asp-for="WayBillweight" class="form-control" />
                <span asp-validation-for="WayBillweight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfParcels" class="control-label"></label>
                <input asp-for="NumberOfParcels" class="form-control" />
                <span asp-validation-for="NumberOfParcels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TritonExpress/Views/TritonExpressWaybills/Index.cshtml
@model IEnumerable<TritonExpress.Models.TritonExpressWaybill>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-primary"><i class="fa fa-plus"></i><b>Add New Waybill</b></a>
</p>
<p>
    @Html.ActionLink("Vehicles", "Index", "TritonExpressVehicles", null, null)
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color" style="float:right">
        <p>
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-secondary" />
        </p>
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"> @Html.DisplayNameFor(model => model.RecipientName)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cell)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]">@Html.DisplayNameFor(model => model.Date)</a>
            </th>
         
            <th>
                @Html.DisplayNameFor(model => model.WayBillweight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfParcels)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RecipientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cell)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
             
                <td>
                    @Html.DisplayFor(modelItem => item.WayBillweight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfParcels)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.wayBillID" class="btn btn-warning"><i class="fa fa-pencil"></i>Edit</a><br/>
                    <a asp-action="Details" asp-route-id="@item.wayBillID" class="btn btn-success"><i class="fa fa-info-circle"></i>Details</a><br/>
                    <a asp-action="Delete" asp-route-id="@item.wayBillID" class="btn btn-danger"><i class="fa fa-trash"></i>Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>